version: '3'

services:
  api:
    image: back_ejemplo
    container_name: api_container
    ports:
      - '3000:3000'
    restart: always

  front:
    image: front_ejemplo
    container_name: front_container
    ports:
      - '5173:5173'
    restart: always
    depends_on:
      - api
    links:
      - api